apiVersion: apps/v1beta1

kind: Deployment

metadata:

  name: demoapp

spec:

  replicas: 1

  strategy:

    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 1

  minReadySeconds: 5 

  template:

    metadata:

      labels:

        app: demoapp

    spec:

      containers:

      - name: demoapp

        image: testacreg.azurecr.io/dockerv6:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 80

        resources:

          requests:

            cpu: 250m

          limits:

            cpu: 500m

---

apiVersion: v1

kind: Service

metadata:

  name: demoapp

spec:

  type: LoadBalancer

  ports:

  - port: 80

  selector:
    app: demoapp