apiVersion: v1
kind: Pod
metadata:
  name: demoapp
  labels:
    app: web
spec:
  containers:
    - name: demoapp
      image: testacreg.azurecr.io/dockerv6:latest
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: mysecret